#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm log.*
decomposePar -force > log.decompose
#pyFoamPrepareCase.py --no-clear --stop-after-templates --no-complain --quiet --no-write-parameters --no-write-report . 2>&1 > log.pyFoam
runParallel $(getApplication)
#python3 script.py
mv postProcessing postProcessingOld
rm -r  0.* 1* 2* 3* 4* 5* 6* 7* 8* 9*
reconstructPar
#decomposePar -force
#------------------------------------------------------------------------------
